// Gene Keys Data and Calculations
// Based on Richard Rudd's Gene Keys system

export interface GeneKey {
  number: number;
  shadow: string;
  gift: string;
  siddhi: string;
  question: string;
  affirmation: string;
  contemplation: string;
}

export interface GeneKeyProfile {
  lifeTheme: GeneKey;        // Sun position
  radiance: GeneKey;         // Earth position
  purpose: GeneKey;          // Jupiter position
  attraction: GeneKey;       // Venus position
  iq: GeneKey;               // Mercury position
  eq: GeneKey;               // Moon position
  sq: GeneKey;               // Saturn position
  coreStability: GeneKey;    // Mars position
  heartStability: GeneKey;   // Neptune position
  spiritualStability: GeneKey; // Uranus position
  fortune: GeneKey;          // Pluto position
  culture: GeneKey;          // North Node position
  pearl: GeneKeySequence;    // 11th Gene Key sequence
}

export interface GeneKeySequence {
  sequence: GeneKey[];
  pearlName: string;
  description: string;
}

// Complete Gene Keys data (1-64)
export const GENE_KEYS: Record<number, GeneKey> = {
  1: {
    number: 1,
    shadow: 'Entropie',
    gift: 'Inspiration',
    siddhi: 'Schöpfung',
    question: 'Was will durch mich geboren werden?',
    affirmation: 'Ich bin ein offener Kanal für göttliche Inspiration.',
    contemplation: 'Betrachte, wie du deine kreative Energie blockierst oder fließen lässt.',
  },
  2: {
    number: 2,
    shadow: 'Dislokation',
    gift: 'Anpassungsfähigkeit',
    siddhi: 'Einheit',
    question: 'Wo kann ich mich dem Fluss des Lebens anvertrauen?',
    affirmation: 'Ich vertraue dem göttlichen Plan und lasse mich führen.',
    contemplation: 'Spüre in die Stille und finde dort deine Verbindung zur Einheit.',
  },
  3: {
    number: 3,
    shadow: 'Chaos',
    gift: 'Innovation',
    siddhi: 'Unsterblichkeit',
    question: 'Welche Veränderung ruft nach meiner Aufmerksamkeit?',
    affirmation: 'Ich umarme das Chaos als Quelle neuer Möglichkeiten.',
    contemplation: 'Betrachte, wie aus dem Chaos neue Ordnung entsteht.',
  },
  4: {
    number: 4,
    shadow: 'Absicht',
    gift: 'Verständnis',
    siddhi: 'Fürbitte',
    question: 'Welche tiefere Wahrheit liegt unter der Oberfläche?',
    affirmation: 'Ich verstehe die verborgene Einheit in allem.',
    contemplation: 'Lausche zwischen den Worten und höre die Stille.',
  },
  5: {
    number: 5,
    shadow: 'Unbeholfenheit',
    gift: 'Geduld',
    siddhi: 'Zeitlosigkeit',
    question: 'Wo kann ich mehr Geduld üben?',
    affirmation: 'Ich bin im Einklang mit dem perfekten Timing des Universums.',
    contemplation: 'Spüre den Rhythmus deines Atems und finde die Ewigkeit im Jetzt.',
  },
  6: {
    number: 6,
    shadow: 'Konflikt',
    gift: 'Diplomatie',
    siddhi: 'Frieden',
    question: 'Wie kann ich Frieden in diese Situation bringen?',
    affirmation: 'Ich bin ein Brückenbauer des Friedens.',
    contemplation: 'Betrachte, wie Konflikte zu tieferem Verständnis führen können.',
  },
  7: {
    number: 7,
    shadow: 'Teilung',
    gift: 'Führung',
    siddhi: 'Vorahnung',
    question: 'Wie kann ich mit Weisheit führen?',
    affirmation: 'Ich führe durch mein Beispiel und meine innere Klarheit.',
    contemplation: 'Spüre die Weisheit, die durch dich hindurchfließt.',
  },
  8: {
    number: 8,
    shadow: 'Voreiligkeit',
    gift: 'Stil',
    siddhi: 'Exquisitheit',
    question: 'Wie kann ich meine einzigartige Gabe ausdrücken?',
    affirmation: 'Ich bin ein Meisterwerk der Schöpfung.',
    contemplation: 'Betrachte die Einzigartigkeit deines Ausdrucks.',
  },
  9: {
    number: 9,
    shadow: 'Trägheit',
    gift: 'Determination',
    siddhi: 'Unerschütterlichkeit',
    question: 'Womit sollte ich mich entschlossen beschäftigen?',
    affirmation: 'Ich bin unerschütterlich in meinem Commitment.',
    contemplation: 'Spüre die Kraft deiner Entschlossenheit.',
  },
  10: {
    number: 10,
    shadow: 'Selbstwertlosigkeit',
    gift: 'Natürlichkeit',
    siddhi: 'Sein',
    question: 'Wer bin ich jenseits aller Rollen?',
    affirmation: 'Ich bin, und das ist genug.',
    contemplation: 'Ruhe in dem, was du bist, ohne etwas tun zu müssen.',
  },
  11: {
    number: 11,
    shadow: 'Dunkelheit',
    gift: 'Idealismus',
    siddhi: 'Licht',
    question: 'Welches Licht will durch mich scheinen?',
    affirmation: 'Ich bin ein Licht in der Welt.',
    contemplation: 'Betrachte, wie selbst die tiefste Dunkelheit Licht hervorbringt.',
  },
  12: {
    number: 12,
    shadow: 'Überheblichkeit',
    gift: 'Bescheidenheit',
    siddhi: 'Reinheit',
    question: 'Wo kann ich demütiger sein?',
    affirmation: 'In meiner Bescheidenheit finde ich wahre Größe.',
    contemplation: 'Spüre die Reinheit, die in einfacher Demut liegt.',
  },
  13: {
    number: 13,
    shadow: 'Abhängigkeit',
    gift: 'Diskretion',
    siddhi: 'Empathie',
    question: 'Wie kann ich tiefer zuhören?',
    affirmation: 'Ich höre die ungesagten Worte und fühle mit.',
    contemplation: 'Lausche mit deinem Herzen und spüre die Empathie.',
  },
  14: {
    number: 14,
    shadow: 'Besitzergreifung',
    gift: 'Kompetenz',
    siddhi: 'Fülle',
    question: 'Wie kann ich meine Ressourcen weise nutzen?',
    affirmation: 'Ich bin ein Kanal für grenzenlose Fülle.',
    contemplation: 'Betrachte, wie Fülle durch Loslassen entsteht.',
  },
  15: {
    number: 15,
    shadow: 'Düsternis',
    gift: 'Magnetismus',
    siddhi: 'Fluss',
    question: 'Wo ist meine Leidenschaft?',
    affirmation: 'Ich bin ein Magnet für alles, was meinem höchsten Gut dient.',
    contemplation: 'Spüre den magnetischen Fluss deiner Lebenskraft.',
  },
  16: {
    number: 16,
    shadow: 'Ignoranz',
    gift: 'Verspieltheit',
    siddhi: 'Zauberei',
    question: 'Wie kann ich mehr Freude in mein Leben bringen?',
    affirmation: 'Ich bin ein Magier der Freude und des Wunders.',
    contemplation: 'Betrachte das Leben als spielerisches Abenteuer.',
  },
  17: {
    number: 17,
    shadow: 'Meinung',
    gift: 'Farsichtigkeit',
    siddhi: 'Offenbarung',
    question: 'Welche Wahrheit wartet darauf, offenbart zu werden?',
    affirmation: 'Ich sehe klar durch den Schleier der Erscheinungen.',
    contemplation: 'Lausche der Offenbarung, die in der Stille kommt.',
  },
  18: {
    number: 18,
    shadow: 'Urteil',
    gift: 'Integrität',
    siddhi: 'Perfektion',
    question: 'Wo kann ich mehr Mitgefühl üben?',
    affirmation: 'Ich sehe die Perfektion in allem, was ist.',
    contemplation: 'Betrachte, wie alles seinen Platz im großen Ganzen hat.',
  },
  19: {
    number: 19,
    shadow: 'Vernachlässigung',
    gift: 'Selbstlosigkeit',
    siddhi: 'Gastfreundschaft',
    question: 'Wie kann ich mehr geben?',
    affirmation: 'Ich gebe bedingungslos und empfange im Geben.',
    contemplation: 'Spüre die Freude, die im Selbstlosen liegt.',
  },
  20: {
    number: 20,
    shadow: 'Resignation',
    gift: 'Selbstermächtigung',
    siddhi: 'Präsenz',
    question: 'Wo bin ich nicht präsent?',
    affirmation: 'Ich bin vollständig im Hier und Jetzt.',
    contemplation: 'Ruhe in der vollkommenen Präsenz dieses Moments.',
  },
  21: {
    number: 21,
    shadow: 'Gier',
    gift: 'Autorität',
    siddhi: 'Befugnis',
    question: 'Wie kann ich verantwortungsvoll führen?',
    affirmation: 'Ich führe mit Weisheit und Mitgefühl.',
    contemplation: 'Betrachte deine wahre Autorität von innen.',
  },
  22: {
    number: 22,
    shadow: 'Moral',
    gift: 'Anmut',
    siddhi: 'Eleganz',
    question: 'Wo kann ich mich öffnen?',
    affirmation: 'Ich bin offen wie ein Kind, das die Welt neu entdeckt.',
    contemplation: 'Spüre die Anmut, die in Offenheit liegt.',
  },
  23: {
    number: 23,
    shadow: 'Überkomplexität',
    gift: 'Einfachheit',
    siddhi: 'Quintessenz',
    question: 'Was ist die Essenz dieser Situation?',
    affirmation: 'In der Einfachheit finde ich die höchste Wahrheit.',
    contemplation: 'Betrachte, wie Komplexität in Einfachheit auflöst.',
  },
  24: {
    number: 24,
    shadow: 'Vergessen',
    gift: 'Erfindung',
    siddhi: 'Erinnerung',
    question: 'Was muss ich mir wieder ins Gedächtnis rufen?',
    affirmation: 'Ich erinnere mich an meine wahre Natur.',
    contemplation: 'Lausche der stillen Stimme der Erinnerung.',
  },
  25: {
    number: 25,
    shadow: 'Verzweiflung',
    gift: 'Heilkunst',
    siddhi: 'Universalität',
    question: 'Wo braucht Heilung statt?',
    affirmation: 'Ich bin ein Kanal für universelle Heilung.',
    contemplation: 'Spüre die heilende Kraft deiner reinen Präsenz.',
  },
  26: {
    number: 26,
    shadow: 'Stolz',
    gift: 'Kunst',
    siddhi: 'Schönheit',
    question: 'Wie kann ich mehr Schönheit erschaffen?',
    affirmation: 'Ich bin ein Künstler des Lebens.',
    contemplation: 'Betrachte die Schönheit in allem, was ist.',
  },
  27: {
    number: 27,
    shadow: 'Selbstverachtung',
    gift: 'Altruismus',
    siddhi: 'Erhabenheit',
    question: 'Wie kann ich mehr lieben?',
    affirmation: 'Ich liebe bedingungslos und grenzenlos.',
    contemplation: 'Spüre die erhabene Natur deines Herzens.',
  },
  28: {
    number: 28,
    shadow: 'Zwecklosigkeit',
    gift: 'Totem',
    siddhi: 'Unsterblichkeit',
    question: 'Was gibt meinem Leben Sinn?',
    affirmation: 'Ich finde Sinn im Hier und Jetzt.',
    contemplation: 'Betrachte den tieferen Zweck deiner Existenz.',
  },
  29: {
    number: 29,
    shadow: 'Halbherzigkeit',
    gift: 'Hingabe',
    siddhi: 'Hingabe',
    question: 'Wem oder was kann ich mich vollständig widmen?',
    affirmation: 'Ich sage Ja zum Leben mit meinem ganzen Sein.',
    contemplation: 'Spüre die Kraft deiner totalen Hingabe.',
  },
  30: {
    number: 30,
    shadow: 'Verlangen',
    gift: 'Leichtigkeit',
    siddhi: 'Ekstase',
    question: 'Wo kann ich loslassen?',
    affirmation: 'In der Leichtigkeit finde ich wahre Freiheit.',
    contemplation: 'Betrachte, wie Verlangen in Ekstase transformiert wird.',
  },
  31: {
    number: 31,
    shadow: 'Arroganz',
    gift: 'Einfluss',
    siddhi: 'Aufrichtigkeit',
    question: 'Wie kann ich authentisch führen?',
    affirmation: 'Ich führe durch meine aufrichtige Präsenz.',
    contemplation: 'Spüre den Einfluss deiner authentischen Natur.',
  },
  32: {
    number: 32,
    shadow: 'Versagen',
    gift: 'Vorhaltung',
    siddhi: 'Vollendung',
    question: 'Was kann ich aus Vergangenem lernen?',
    affirmation: 'Ich bin vollendet, wie ich bin.',
    contemplation: 'Betrachte, wie Vergangenheit zur Weisheit wird.',
  },
  33: {
    number: 33,
    shadow: 'Rückzug',
    gift: 'Anerkennung',
    siddhi: 'Wahrheit',
    question: 'Welche Wahrheit wartet darauf, erkannt zu werden?',
    affirmation: 'Ich erkenne die Wahrheit in mir selbst.',
    contemplation: 'Lausche der stillen Wahrheit deines Herzens.',
  },
  34: {
    number: 34,
    shadow: 'Gewalt',
    gift: 'Stärke',
    siddhi: 'Majestät',
    question: 'Wie kann ich meine Kraft weise nutzen?',
    affirmation: 'Meine Kraft dient dem höchsten Gut aller.',
    contemplation: 'Spüre die majestätische Kraft deines Seins.',
  },
  35: {
    number: 35,
    shadow: 'Langeweile',
    gift: 'Vorstellungskraft',
    siddhi: 'Unendlichkeit',
    question: 'Was will durch mich erschaffen werden?',
    affirmation: 'Meine Vorstellungskraft erschafft neue Welten.',
    contemplation: 'Betrachte die unendlichen Möglichkeiten deines Geistes.',
  },
  36: {
    number: 36,
    shadow: 'Angst',
    gift: 'Empathie',
    siddhi: 'Mitgefühl',
    question: 'Welche Angst darf geheilt werden?',
    affirmation: 'In meinem Mitgefühl heile ich die Welt.',
    contemplation: 'Spüre das Mitgefühl, das alle Angst auflöst.',
  },
  37: {
    number: 37,
    shadow: 'Schwäche',
    gift: 'Gleichgewicht',
    siddhi: 'Würde',
    question: 'Wo brauche ich mehr Gleichgewicht?',
    affirmation: 'In meinem Gleichgewicht finde ich wahre Stärke.',
    contemplation: 'Betrachte das Gleichgewicht aller Kräfte in dir.',
  },
  38: {
    number: 38,
    shadow: 'Sturheit',
    gift: 'Dynamik',
    siddhi: 'Grenzenlosigkeit',
    question: 'Wogegen kämpfe ich an?',
    affirmation: 'Ich bin grenzenlos in meiner Dynamik.',
    contemplation: 'Spüre die grenzenlose Dynamik deines Lebens.',
  },
  39: {
    number: 39,
    shadow: 'Wut',
    gift: 'Durchsetzungsvermögen',
    siddhi: 'Befreiung',
    question: 'Was will befreit werden?',
    affirmation: 'Ich bin ein Kanal für Befreiung.',
    contemplation: 'Betrachte, wie Wut in Befreiung transformiert wird.',
  },
  40: {
    number: 40,
    shadow: 'Einsamkeit',
    gift: 'Vorantreiben',
    siddhi: 'Wunder',
    question: 'Welches Wunder wartet auf mich?',
    affirmation: 'Ich bin offen für Wunder in meinem Leben.',
    contemplation: 'Spüre das Wunder deiner Existenz.',
  },
  41: {
    number: 41,
    shadow: 'Fantasie',
    gift: 'Antizipation',
    siddhi: 'Emanzipation',
    question: 'Wovon träume ich?',
    affirmation: 'Ich bin frei in meinen Träumen und Visionen.',
    contemplation: 'Betrachte die emanzipierende Kraft deiner Visionen.',
  },
  42: {
    number: 42,
    shadow: 'Abweisung',
    gift: 'Detachment',
    siddhi: 'Reichtum',
    question: 'Was kann ich loslassen?',
    affirmation: 'Im Loslassen finde ich wahren Reichtum.',
    contemplation: 'Spüre den Reichtum, der im Nicht-Anhaften liegt.',
  },
  43: {
    number: 43,
    shadow: 'Widerstand',
    gift: 'Einsicht',
    siddhi: 'Erleuchtung',
    question: 'Welche Einsicht wartet darauf, erkannt zu werden?',
    affirmation: 'Ich bin ein Kanal für göttliche Einsicht.',
    contemplation: 'Lausche der erleuchtenden Einsicht deines Herzens.',
  },
  44: {
    number: 44,
    shadow: 'Interferenz',
    gift: 'Teamwork',
    siddhi: 'Synthese',
    question: 'Wie kann ich besser zusammenarbeiten?',
    affirmation: 'In der Synthese finde ich wahre Kraft.',
    contemplation: 'Betrachte die synthetische Kraft der Zusammenarbeit.',
  },
  45: {
    number: 45,
    shadow: 'Dominanz',
    gift: 'Synergie',
    siddhi: 'Communion',
    question: 'Wie kann ich mehr teilen?',
    affirmation: 'In der Gemeinschaft finde ich wahre Fülle.',
    contemplation: 'Spüre die kommunionierende Kraft des Teilens.',
  },
  46: {
    number: 46,
    shadow: 'Seriosität',
    gift: 'Delight',
    siddhi: 'Ekstase',
    question: 'Wo kann ich mehr Freude finden?',
    affirmation: 'Ich bin ein Ausdruck göttlicher Freude.',
    contemplation: 'Betrachte die ekstatische Natur deines Seins.',
  },
  47: {
    number: 47,
    shadow: 'Oppression',
    gift: 'Transmutation',
    siddhi: 'Transfiguration',
    question: 'Was will in mir transformiert werden?',
    affirmation: 'Ich bin ein Alchemist der Seele.',
    contemplation: 'Spüre die transfigurierende Kraft deines Bewusstseins.',
  },
  48: {
    number: 48,
    shadow: 'Unwissenheit',
    gift: 'Weisheit',
    siddhi: 'Allwissenheit',
    question: 'Welche Weisheit sucht mich?',
    affirmation: 'Ich bin ein Kanal für universelle Weisheit.',
    contemplation: 'Lausche der allwissenden Stille deines Herzens.',
  },
  49: {
    number: 49,
    shadow: 'Reaktion',
    gift: 'Revolution',
    siddhi: 'Transformation',
    question: 'Was will sich transformieren?',
    affirmation: 'Ich bin ein Agent der Transformation.',
    contemplation: 'Betrachte die transformierende Kraft deiner Präsenz.',
  },
  50: {
    number: 50,
    shadow: 'Verantwortung',
    gift: 'Verantwortlichkeit',
    siddhi: 'Sanktuarium',
    question: 'Wofür übernehme ich Verantwortung?',
    affirmation: 'Ich bin ein Sanktuarium für alle Wesen.',
    contemplation: 'Spüre die sanktuierende Kraft deiner Verantwortung.',
  },
  51: {
    number: 51,
    shadow: 'Aggression',
    gift: 'Initiative',
    siddhi: 'Erweckung',
    question: 'Was will durch mich initiiert werden?',
    affirmation: 'Ich bin ein Wecker der Menschheit.',
    contemplation: 'Betrachte die erweckende Kraft deiner Initiative.',
  },
  52: {
    number: 52,
    shadow: 'Anspannung',
    gift: 'Konzentration',
    siddhi: 'Stille',
    question: 'Wo brauche ich mehr Stille?',
    affirmation: 'In der Stille finde ich alles.',
    contemplation: 'Ruhe in der vollkommenen Stille deines Seins.',
  },
  53: {
    number: 53,
    shadow: 'Unsicherheit',
    gift: 'Expansion',
    siddhi: 'Liebe',
    question: 'Wohin will ich mich erweitern?',
    affirmation: 'Ich bin ein Ausdruck grenzenloser Liebe.',
    contemplation: 'Spüre die expandierende Kraft deiner Liebe.',
  },
  54: {
    number: 54,
    shadow: 'Gier',
    gift: 'Aspiration',
    siddhi: 'Akzeptanz',
    question: 'Was will ich wirklich?',
    affirmation: 'In der Akzeptanz finde ich Erfüllung.',
    contemplation: 'Betrachte, wie Aspiration in Akzeptanz mündet.',
  },
  55: {
    number: 55,
    shadow: 'Eifersucht',
    gift: 'Freiheit',
    siddhi: 'Freiheit',
    question: 'Wo bin ich nicht frei?',
    affirmation: 'Ich bin frei in meinem Geist und Herzen.',
    contemplation: 'Spüre die Freiheit, die deine wahre Natur ist.',
  },
  56: {
    number: 56,
    shadow: 'Distraction',
    gift: 'Reichhaltigkeit',
    siddhi: 'Fülle',
    question: 'Wo ist meine Fülle?',
    affirmation: 'Ich bin ein Ausdruck göttlicher Fülle.',
    contemplation: 'Betrachte die reichhaltige Natur deines Lebens.',
  },
  57: {
    number: 57,
    shadow: 'Verwirrung',
    gift: 'Intuition',
    siddhi: 'Klarheit',
    question: 'Welche Klarheit suche ich?',
    affirmation: 'Ich bin ein Kanal für göttliche Klarheit.',
    contemplation: 'Lausche der intuitiven Klarheit deines Herzens.',
  },
  58: {
    number: 58,
    shadow: 'Unzufriedenheit',
    gift: 'Vitalität',
    siddhi: 'Unsterblichkeit',
    question: 'Wo ist meine Lebendigkeit?',
    affirmation: 'Ich bin ein Ausdruck unsterblicher Vitalität.',
    contemplation: 'Spüre die unsterbliche Vitalität deines Seins.',
  },
  59: {
    number: 59,
    shadow: 'Unehrlichkeit',
    gift: 'Intimität',
    siddhi: 'Transparenz',
    question: 'Wo kann ich mich öffnen?',
    affirmation: 'Ich bin transparent wie Kristall.',
    contemplation: 'Betrachte die transparenze Natur deiner Seele.',
  },
  60: {
    number: 60,
    shadow: 'Mangel',
    gift: 'Realismus',
    siddhi: 'Justice',
    question: 'Wo sehe ich Mangel statt Fülle?',
    affirmation: 'In der Gerechtigkeit finde ich wahre Balance.',
    contemplation: 'Spüre die gerechte Balance allen Seins.',
  },
  61: {
    number: 61,
    shadow: 'Intellektualität',
    gift: 'Inspiration',
    siddhi: 'Sanftmut',
    question: 'Welche Inspiration sucht mich?',
    affirmation: 'Ich bin ein Kanal für göttliche Inspiration.',
    contemplation: 'Lausche der inspirierenden Stille deines Herzens.',
  },
  62: {
    number: 62,
    shadow: 'Selbstzweifel',
    gift: 'Präzision',
    siddhi: 'Unfehlbarkeit',
    question: 'Wo zweifle ich an mir?',
    affirmation: 'Ich bin unfehlbar in meiner wahren Natur.',
    contemplation: 'Betrachte die unfehlbare Präzision deines Seins.',
  },
  63: {
    number: 63,
    shadow: 'Doubt',
    gift: 'Inquiry',
    siddhi: 'Truth',
    question: 'Welche Wahrheit suche ich?',
    affirmation: 'Ich bin ein Sucher der Wahrheit.',
    contemplation: 'Spüre die wahrheitssuchende Natur deines Herzens.',
  },
  64: {
    number: 64,
    shadow: 'Verwirrung',
    gift: 'Imagination',
    siddhi: 'Illumination',
    question: 'Was will durch mich erleuchtet werden?',
    affirmation: 'Ich bin ein Kanal für göttliche Erleuchtung.',
    contemplation: 'Betrachte die illuminierende Kraft deiner Vorstellungskraft.',
  },
};

// Pearl sequences for each Gene Key
export const PEARL_SEQUENCES: Record<number, { name: string; sequence: number[]; description: string }> = {
  1: { name: 'Die Perle der Schöpfung', sequence: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], description: 'Der Weg der kreativen Manifestation' },
  2: { name: 'Die Perle der Einheit', sequence: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], description: 'Der Weg der universellen Verbindung' },
  3: { name: 'Die Perle der Unsterblichkeit', sequence: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], description: 'Der Weg der ewigen Veränderung' },
  4: { name: 'Die Perle der Fürbitte', sequence: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], description: 'Der Weg des verstehenden Herzens' },
  5: { name: 'Die Perle der Zeitlosigkeit', sequence: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], description: 'Der Weg des ewigen Rhythmus' },
  6: { name: 'Die Perle des Friedens', sequence: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], description: 'Der Weg der harmonischen Lösung' },
  7: { name: 'Die Perle der Vorahnung', sequence: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], description: 'Der Weg der weisen Führung' },
  8: { name: 'Die Perle der Exquisitheit', sequence: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18], description: 'Der Weg des künstlerischen Ausdrucks' },
  9: { name: 'Die Perle der Unerschütterlichkeit', sequence: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], description: 'Der Weg der fokussierten Kraft' },
  10: { name: 'Die Perle des Seins', sequence: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], description: 'Der Weg der selbstlosen Natur' },
  11: { name: 'Die Perle des Lichts', sequence: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21], description: 'Der Weg der inneren Erleuchtung' },
  12: { name: 'Die Perle der Reinheit', sequence: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22], description: 'Der Weg der bescheidenen Größe' },
  13: { name: 'Die Perle der Empathie', sequence: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23], description: 'Der Weg des fühlenden Herzens' },
  14: { name: 'Die Perle der Fülle', sequence: [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24], description: 'Der Weg des wohlhabenden Geistes' },
  15: { name: 'Die Perle des Flusses', sequence: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], description: 'Der Weg der magnetischen Anziehung' },
  16: { name: 'Die Perle der Zauberei', sequence: [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26], description: 'Der Weg des verspielten Genies' },
  17: { name: 'Die Perle der Offenbarung', sequence: [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27], description: 'Der Weg der fernsehenden Wahrheit' },
  18: { name: 'Die Perle der Perfektion', sequence: [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], description: 'Der Weg des mitfühlenden Blicks' },
  19: { name: 'Die Perle der Gastfreundschaft', sequence: [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], description: 'Der Weg des selbstlosen Gebens' },
  20: { name: 'Die Perle der Präsenz', sequence: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], description: 'Der Weg des hier und jetzt' },
  21: { name: 'Die Perle der Befugnis', sequence: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], description: 'Der Weg der verantwortungsvollen Führung' },
  22: { name: 'Die Perle der Eleganz', sequence: [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32], description: 'Der Weg der anmutigen Offenheit' },
  23: { name: 'Die Perle der Quintessenz', sequence: [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33], description: 'Der Weg der einfachen Wahrheit' },
  24: { name: 'Die Perle der Erinnerung', sequence: [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34], description: 'Der Weg der silencen Rückkehr' },
  25: { name: 'Die Perle der Universalität', sequence: [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35], description: 'Der Weg der universellen Heilung' },
  26: { name: 'Die Perle der Schönheit', sequence: [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36], description: 'Der Weg der künstlerischen Magie' },
  27: { name: 'Die Perle der Erhabenheit', sequence: [27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37], description: 'Der Weg des altruistischen Herzens' },
  28: { name: 'Die Perle der Unsterblichkeit', sequence: [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38], description: 'Der Weg des sinnvollen Kampfes' },
  29: { name: 'Die Perle der Hingabe', sequence: [29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39], description: 'Der Weg des bedingungslosen Ja' },
  30: { name: 'Die Perle der Ekstase', sequence: [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40], description: 'Der Weg der leichten Leidenschaft' },
  31: { name: 'Die Perle der Aufrichtigkeit', sequence: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41], description: 'Der Weg des authentischen Einflusses' },
  32: { name: 'Die Perle der Vollendung', sequence: [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42], description: 'Der Weg der vollständigen Erinnerung' },
  33: { name: 'Die Perle der Wahrheit', sequence: [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43], description: 'Der Weg des stillen Erkennens' },
  34: { name: 'Die Perle der Majestät', sequence: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44], description: 'Der Weg der majestätischen Kraft' },
  35: { name: 'Die Perle der Unendlichkeit', sequence: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45], description: 'Der Weg der grenzenlosen Vorstellung' },
  36: { name: 'Die Perle des Mitgefühls', sequence: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46], description: 'Der Weg der empathischen Heilung' },
  37: { name: 'Die Perle der Würde', sequence: [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47], description: 'Der Weg des starken Gleichgewichts' },
  38: { name: 'Die Perle der Grenzenlosigkeit', sequence: [38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48], description: 'Der Weg der dynamischen Freiheit' },
  39: { name: 'Die Perle der Befreiung', sequence: [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49], description: 'Der Weg der durchsetzenden Freiheit' },
  40: { name: 'Die Perle des Wunders', sequence: [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50], description: 'Der Weg des vorantreibenden Wunders' },
  41: { name: 'Die Perle der Emanzipation', sequence: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51], description: 'Der Weg der emanzipierten Vision' },
  42: { name: 'Die Perle des Reichtums', sequence: [42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52], description: 'Der Weg des reichhaltigen Loslassens' },
  43: { name: 'Die Perle der Erleuchtung', sequence: [43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53], description: 'Der Weg der einsichtigen Wahrheit' },
  44: { name: 'Die Perle der Synthese', sequence: [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54], description: 'Der Weg der synthetischen Teamwork' },
  45: { name: 'Die Perle der Communion', sequence: [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55], description: 'Der Weg der kommunionierenden Synergie' },
  46: { name: 'Die Perle der Ekstase', sequence: [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56], description: 'Der Weg der delightful Freude' },
  47: { name: 'Die Perle der Transfiguration', sequence: [47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57], description: 'Der Weg der transmutierenden Alchemie' },
  48: { name: 'Die Perle der Allwissenheit', sequence: [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58], description: 'Der Weg der weisen Klarheit' },
  49: { name: 'Die Perle der Transformation', sequence: [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59], description: 'Der Weg der revolutionären Veränderung' },
  50: { name: 'Die Perle des Sanktuariums', sequence: [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60], description: 'Der Weg des verantwortlichen Schutzes' },
  51: { name: 'Die Perle der Erweckung', sequence: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61], description: 'Der Weg der initiativen Erweckung' },
  52: { name: 'Die Perle der Stille', sequence: [52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62], description: 'Der Weg der konzentrierten Ruhe' },
  53: { name: 'Die Perle der Liebe', sequence: [53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63], description: 'Der Weg der expandierenden Liebe' },
  54: { name: 'Die Perle der Akzeptanz', sequence: [54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64], description: 'Der Weg der aspiranten Erfüllung' },
  55: { name: 'Die Perle der Freiheit', sequence: [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 1], description: 'Der Weg der befreiten Leidenschaft' },
  56: { name: 'Die Perle der Fülle', sequence: [56, 57, 58, 59, 60, 61, 62, 63, 64, 1, 2], description: 'Der Weg der reichhaltigen Abundanz' },
  57: { name: 'Die Perle der Klarheit', sequence: [57, 58, 59, 60, 61, 62, 63, 64, 1, 2, 3], description: 'Der Weg der intuitiven Wahrheit' },
  58: { name: 'Die Perle der Unsterblichkeit', sequence: [58, 59, 60, 61, 62, 63, 64, 1, 2, 3, 4], description: 'Der Weg der vitalen Ewigkeit' },
  59: { name: 'Die Perle der Transparenz', sequence: [59, 60, 61, 62, 63, 64, 1, 2, 3, 4, 5], description: 'Der Weg der intimen Offenheit' },
  60: { name: 'Die Perle der Justice', sequence: [60, 61, 62, 63, 64, 1, 2, 3, 4, 5, 6], description: 'Der Weg der realistischen Gerechtigkeit' },
  61: { name: 'Die Perle der Sanftmut', sequence: [61, 62, 63, 64, 1, 2, 3, 4, 5, 6, 7], description: 'Der Weg der inspirierten Weisheit' },
  62: { name: 'Die Perle der Unfehlbarkeit', sequence: [62, 63, 64, 1, 2, 3, 4, 5, 6, 7, 8], description: 'Der Weg der präzisen Wahrheit' },
  63: { name: 'Die Perle der Wahrheit', sequence: [63, 64, 1, 2, 3, 4, 5, 6, 7, 8, 9], description: 'Der Weg der inquirischen Erkenntnis' },
  64: { name: 'Die Perle der Illumination', sequence: [64, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], description: 'Der Weg der imaginativen Erleuchtung' },
};

// Get Gene Key by number
export function getGeneKey(number: number): GeneKey | undefined {
  return GENE_KEYS[number];
}

// Get Pearl sequence by Gene Key number
export function getPearlSequence(number: number): GeneKeySequence | undefined {
  const pearl = PEARL_SEQUENCES[number];
  if (!pearl) return undefined;
  
  return {
    sequence: pearl.sequence.map(n => GENE_KEYS[n]),
    pearlName: pearl.name,
    description: pearl.description,
  };
}

// Calculate Gene Key profile from birth data
export function calculateGeneKeyProfile(
  sunGate: number,
  earthGate: number,
  moonGate: number,
  mercuryGate: number,
  venusGate: number,
  marsGate: number,
  jupiterGate: number,
  saturnGate: number,
  uranusGate: number,
  neptuneGate: number,
  plutoGate: number,
  northNodeGate: number
): GeneKeyProfile {
  return {
    lifeTheme: GENE_KEYS[sunGate],
    radiance: GENE_KEYS[earthGate],
    purpose: GENE_KEYS[jupiterGate],
    attraction: GENE_KEYS[venusGate],
    iq: GENE_KEYS[mercuryGate],
    eq: GENE_KEYS[moonGate],
    sq: GENE_KEYS[saturnGate],
    coreStability: GENE_KEYS[marsGate],
    heartStability: GENE_KEYS[neptuneGate],
    spiritualStability: GENE_KEYS[uranusGate],
    fortune: GENE_KEYS[plutoGate],
    culture: GENE_KEYS[northNodeGate],
    pearl: getPearlSequence(sunGate)!,
  };
}

// Get contemplation for a specific Gene Key
export function getContemplation(number: number): string {
  return GENE_KEYS[number]?.contemplation || '';
}

// Get affirmation for a specific Gene Key
export function getAffirmation(number: number): string {
  return GENE_KEYS[number]?.affirmation || '';
}
